name: Deploy Content to sentinel [f3aa07e8-afa5-408f-9540-b7b11bca5adc]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-f3aa07e8-afa5-408f-9540-b7b11bca5adc.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ master ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-f3aa07e8-afa5-408f-9540-b7b11bca5adc.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'sentinel'
      workspaceName: 'sentinel'
      workspaceId: 'c9c6dfdc-1403-467a-b1b8-b491ce89d2d5'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule,AutomationRule,HuntingQuery,Parser,Playbook,Workbook'
      branch: 'master'
      sourceControlId: 'f3aa07e8-afa5-408f-9540-b7b11bca5adc'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_f3aa07e8afa5408f9540b7b11bca5adc }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_f3aa07e8afa5408f9540b7b11bca5adc }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_f3aa07e8afa5408f9540b7b11bca5adc }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_f3aa07e8afa5408f9540b7b11bca5adc }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_f3aa07e8afa5408f9540b7b11bca5adc }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_f3aa07e8afa5408f9540b7b11bca5adc }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_f3aa07e8afa5408f9540b7b11bca5adc }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_f3aa07e8afa5408f9540b7b11bca5adc }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_f3aa07e8afa5408f9540b7b11bca5adc }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-f3aa07e8-afa5-408f-9540-b7b11bca5adc.ps1